### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LRISEM** [werleycordeiro/Kalman-Filter-Dynamic-Nelson-Siegel#1]
When I run the program opt.py, I get the following error:

TypeError: order must be str, not int

**Comment by LRISEM** [comment]
this is the detailed error code:
Traceback (most recent call last):
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
TypeError: order must be str, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuenmao/IProgram/PycharmProjects/DLMU_Project/Options_Futures_OtherDerivatives/期限结构/Kalman-Filter-Dynamic-Nelson-Siegel-master/opt.py", line 39, in <module>
    reso = optimize.minimize(fun=kalman, x0=para, args=(df, lik, prev, ahead, matu), method='L-BFGS-B', bounds=bnds,
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/scipy/optimize/_minimize.py", line 623, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 140, in __init__
    self._update_fun()
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 233, in _update_fun
    self._update_fun_impl()
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in update_fun
    self.f = fun_wrapped(self.x)
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 134, in fun_wrapped
    return fun(np.copy(x), *args)
  File "/Users/liuenmao/IProgram/PycharmProjects/DLMU_Project/Options_Futures_OtherDerivatives/期限结构/Kalman-Filter-Dynamic-Nelson-Siegel-master/DNS_baseline.py", line 65, in kalman
    P_t[:,:,0] = lyapunov(N=N,phi=phi,Q=Q)
  File "/Users/liuenmao/IProgram/PycharmProjects/DLMU_Project/Options_Futures_OtherDerivatives/期限结构/Kalman-Filter-Dynamic-Nelson-Siegel-master/lyapunov.py", line 3, in lyapunov
    return(np.matmul(np.linalg.inv(np.identity(N**2) - np.kron(phi,phi)), np.reshape(Q,(N**2),1)).reshape((N,N)))
  File "<__array_function__ internals>", line 5, in reshape
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/liuenmao/软件/anaconda3/python.app/Contents/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: order must be str, not int

**Comment by LRISEM** [comment]
@werleycordeiro

**Comment by werleycordeiro** [comment]
Thanks for posting. I'm swamped for the next few months so I won't be able to take a close look.

But, you can follow this example: https://github.com/werleycordeiro/Examples/blob/main/Tutorial_Package_py.ipynb
